spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.11:3306/mojishowcase?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    druid:
      filters: config,wall,stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      initial-size: 5 #初始化数量
      min-idle: 3  #最小连接池数量
      max-active: 20 #最大连接池数量
      max-wait: 60000 #连接超时时间
      pool-prepared-statements: true #打开psCache, 对支持游标的数据库性能提升巨大
      max-pool-prepared-statement-per-connection-size: 20 #指定每个连接PsCache的大小
      time-between-eviction-runs-millis: 6000 #配置间隔多久检测需要关闭的空闲连接，单位毫秒
      min-evictable-idle-time-millis: 300000 #空闲连接多久后可被清除，单位毫秒
      validation-query: select 'x' #验证数据库连接的查询语句
      test-while-idle: true #当连接空闲时，是否执行连接测试
      test-on-borrow: false #当从连接池借用连接时，是否测试该连接
      test-on-return: false #在连接归还到连接池时是否测试该连接
      connection-init-sqls: set names utf8mb4;